# Preprocessing dataset

This notebook contains steps for processing available dataset to find insights and make it suitable for training

---

## Libraries

In [184]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

## Import dataset

In [185]:
df = pd.read_csv('dataset.csv')
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [186]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   str
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   str
dtypes: int64(1), str(11)
memory usage: 376.0 KB

The dataset contains values that need transformation before training.

## Preprocessing

---

- `model_year`

In [187]:
df.model_year.unique()

array([2013, 2021, 2022, 2015, 2016, 2017, 2001, 2020, 2019, 2003, 2018,
       2023, 2000, 2006, 2011, 2012, 2007, 2014, 2005, 2009, 2010, 2004,
       2008, 1997, 1999, 1993, 2002, 1998, 2024, 1996, 1974, 1992, 1995,
       1994])

The 'model_year' column is in thousands, converting it in 'age' that can reduce the scale

In [188]:
df['vehicle_age'] = 2026 - df.model_year
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,vehicle_age
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300",13
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005",5
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598",4
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500",11
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999",5

In [189]:
df = df.drop(columns=['model_year'])
df.head()

,brand,model,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,vehicle_age
0,Ford,Utility Police Interceptor Base,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300",13
1,Hyundai,Palisade SEL,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005",5
2,Lexus,RX 350 RX 350,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598",4
3,INFINITI,Q50 Hybrid Sport,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500",11
4,Audi,Q3 45 S line Premium Plus,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999",5

---

- `milage`

In [190]:
df.milage.unique()

<StringArray>
[ '51,000 mi.',  '34,742 mi.',  '22,372 mi.',  '88,900 mi.',   '9,835 mi.',
 '136,397 mi.',  '84,000 mi.', '242,000 mi.',  '23,436 mi.',  '34,000 mi.',
 ...
  '39,611 mi.', '154,860 mi.',   '7,008 mi.',  '21,057 mi.',  '39,750 mi.',
  '71,312 mi.',  '32,250 mi.',  '53,705 mi.',     '714 mi.',   '2,116 mi.']
Length: 2818, dtype: str

Converting milage values into integer after removing comma and string

In [191]:
df['milage'] = df.milage.str.replace(r"[^0-9]", "", regex=True).astype(int)

In [192]:
df.head()

,brand,model,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,vehicle_age
0,Ford,Utility Police Interceptor Base,51000,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300",13
1,Hyundai,Palisade SEL,34742,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005",5
2,Lexus,RX 350 RX 350,22372,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598",4
3,INFINITI,Q50 Hybrid Sport,88900,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500",11
4,Audi,Q3 45 S line Premium Plus,9835,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999",5

Scale milage column to a smaller value

In [193]:
scaler = StandardScaler()
df['milage'] = scaler.fit_transform(df[['milage']])

In [194]:
df.head()

,brand,model,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,vehicle_age
0,Ford,Utility Police Interceptor Base,-0.262336,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300",13
1,Hyundai,Palisade SEL,-0.573255,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005",5
2,Lexus,RX 350 RX 350,-0.809820,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598",4
3,INFINITI,Q50 Hybrid Sport,0.462467,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500",11
4,Audi,Q3 45 S line Premium Plus,-1.049579,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999",5

---

- `fuel_type`

In [195]:
df['fuel_type'].unique()

<StringArray>
[ 'E85 Flex Fuel',       'Gasoline',         'Hybrid',              nan,
         'Diesel', 'Plug-In Hybrid',              '–',  'not supported']
Length: 8, dtype: str

There are 'nan' values

In [196]:
df.fillna("Unknown", inplace=True)
df[df['fuel_type'] == "Unknown"]

,brand,model,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,vehicle_age
9,Tesla,Model X Long Range Plus,-0.587445,Unknown,534.0HP Electric Motor Electric Fuel System,A/T,Black,Black,None reported,Yes,"$69,950",6
44,Lucid,Air Grand Touring,-1.169735,Unknown,536.0HP Electric Motor Electric Fuel System,1-Speed A/T,Red,Beige,None reported,Yes,"$119,999",4
68,Lucid,Air Grand Touring,-1.143956,Unknown,536.0HP Electric Motor Electric Fuel System,1-Speed A/T,Red,Black,None reported,Yes,"$99,000",4
92,Rivian,R1S Adventure Package,-1.184117,Unknown,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,White,Green,None reported,Yes,"$92,000",3
122,Rivian,R1S Adventure Package,-1.189854,Unknown,835.0HP Electric Motor Electric Fuel System,A/T,Green,White,None reported,Yes,"$94,000",3
...,...,...,...,...,...,...,...,...,...,...,...,...
3908,Tesla,Model Y Long Range,-0.295765,Unknown,Electric,1-Speed Automatic,Deep Blue Metallic,Black,None reported,Unknown,"$37,999",5
3913,Tesla,Model S 100D,0.005402,Unknown,518.0HP Electric Motor Electric Fuel System,A/T,Blue,Black,None reported,Yes,"$41,000",8
3932,Tesla,Model X Performance,-0.749331,Unknown,778.0HP Electric Motor Electric Fuel System,A/T,White,Beige,None reported,Yes,"$68,969",6
3961,Tesla,Model 3 Long Range,-0.783486,Unknown,Electric,1-Speed Automatic,White,Black,None reported,Unknown,"$35,999",5
4006,Porsche,Taycan,-1.197198,Unknown,Electric,Automatic,Black,Black,None reported,Unknown,"$90,998",4

'nan' values represent electric vehicles. Columns containing these values cannot be dropped

Label encoding `fuel_type` values

In [197]:
le = LabelEncoder()
df['fuel_type'] = le.fit_transform(df['fuel_type'])
df.head()

,brand,model,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,vehicle_age
0,Ford,Utility Police Interceptor Base,-0.262336,1,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300",13
1,Hyundai,Palisade SEL,-0.573255,2,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005",5
2,Lexus,RX 350 RX 350,-0.809820,2,3.5 Liter DOHC,Automatic,Blue,Black,None reported,Unknown,"$54,598",4
3,INFINITI,Q50 Hybrid Sport,0.462467,3,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500",11
4,Audi,Q3 45 S line Premium Plus,-1.049579,2,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,Unknown,"$34,999",5

In [198]:
df['fuel_type'].unique()

array([1, 2, 3, 5, 0, 4, 7, 6])

---

- `engine`

In [199]:
df['engine'].unique()

<StringArray>
[        '300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability',
                                         '3.8L V6 24V GDI DOHC',
                                               '3.5 Liter DOHC',
          '354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid',
                                   '2.0L I4 16V GDI DOHC Turbo',
                                                    '2.4 Liter',
                 '292.0HP 2.0L 4 Cylinder Engine Gasoline Fuel',
                 '282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel',
                '311.0HP 3.5L V6 Cylinder Engine Gasoline Fuel',
                  '534.0HP Electric Motor Electric Fuel System',
 ...
                 '200.0HP 1.6L 4 Cylinder Engine Gasoline Fuel',
                 '227.0HP 2.0L 4 Cylinder Engine Gasoline Fuel',
 '201.0HP 2.0L 4 Cylinder Engine Gasoline/Mild Electric Hybrid',
                '242.0HP 3.3L V6 Cylinder Engine Gasoline Fuel',
                 '355.0HP 2.0L 4 Cylinder Engine Gasoline Fuel',
                 '400.0HP 5.0L 8 Cylinder Engine Gasoline Fuel',
                   '211.0HP 2.0L 4 Cylinder Engine Diesel Fuel',
                 '136.0HP 1.8L 4 Cylinder Engine Gasoline Fuel',
                 '270.0HP 2.0L 4 Cylinder Engine Gasoline Fuel',
                '420.0HP 5.9L 12 Cylinder Engine Gasoline Fuel']
Length: 1146, dtype: str

The `engine` column has many unique values. It has useful insights including HP, engine cylinder and liters. Extract these important features

Extract HP, engine size, and cylinders into separate columns

In [200]:
df['HP'] = df['engine'].str.extract(r'(\d+\.?\d*)HP').astype(float)

In [201]:
df['engine_size'] = df['engine'].str.extract(r'(\d+\.?\d*)L').astype(float)

In [202]:
df['cylinders'] = df['engine'].str.extract(r'V(\d+)').astype(float)

In [203]:
df.head()

,brand,model,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,vehicle_age,HP,engine_size,cylinders
0,Ford,Utility Police Interceptor Base,-0.262336,1,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300",13,300.0,3.7,6.0
1,Hyundai,Palisade SEL,-0.573255,2,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005",5,NaN,3.8,6.0
2,Lexus,RX 350 RX 350,-0.809820,2,3.5 Liter DOHC,Automatic,Blue,Black,None reported,Unknown,"$54,598",4,NaN,NaN,NaN
3,INFINITI,Q50 Hybrid Sport,0.462467,3,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500",11,354.0,3.5,6.0
4,Audi,Q3 45 S line Premium Plus,-1.049579,2,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,Unknown,"$34,999",5,NaN,2.0,NaN

In [204]:
df['cylinders'].isnull().sum()

np.int64(2799)

`cylinders` has lot of null values, so drop the column

In [205]:
df = df.drop(columns=['cylinders'])

In [206]:
df['HP'].isnull().sum()

np.int64(808)

In [207]:
df['HP'].unique()

array([ 300.,   nan,  354.,  292.,  282.,  311.,  534.,  715.,  382.,
        400.,  375.,  305.,  287.,  550.,  120.,  355.,  276.,  445.,
        362.,  345.,  383.,  180.,  211.,  173.,  240.,  552.,  536.,
        310.,  228.,  268.,  503.,  325.,  208.,  250.,  200.,  420.,
        302.,  306.,  237.,  248.,  425.,  582.,  444.,  335.,  424.,
        340.,  225.,  365.,  315.,  199.,  560.,  326.,  165.,  835.,
        241.,  215.,  130.,  288.,  369.,  195.,  285.,  485.,  132.,
        416.,  360.,  280.,  620.,  265.,  469.,  169.,  330.,  275.,
        303.,  450.,  651.,  255.,  455.,  182.,  236.,  370.,  212.,
        565.,  230.,  171.,  252.,  220.,  188.,  235.,  320.,  138.,
        291.,  523.,  440.,  181.,  429.,  263.,  210.,  404.,  670.,
        563.,  283.,  150.,  266.,  328.,  304.,  381.,  493.,  641.,
        760.,  329.,  239.,  160.,  402.,  166.,  390.,  147.,  357.,
        271.,  350.,  611.,  295.,  603.,  454.,  490.,  301.,  395.,
        272.,  437.,  323.,  256.,  140.,  600.,  409.,  640.,  204.,
        316.,  591.,  219.,  505.,  403.,  170.,  115.,  562.,  106.,
        201.,  496.,  475.,  184.,  407.,  543.,  333.,  553.,  471.,
        380.,  247.,  349.,  190.,  410.,  260.,  245.,  332.,  261.,
        107.,  577.,  290.,  453.,  293.,  139.,  389.,  567.,  221.,
        518.,  630.,  218.,  385.,  174.,  134.,  273.,  172.,  542.,
        571.,  601.,  500.,  270.,  161.,  394.,  520.,  164.,  205.,
        308.,  226.,  227.,  412.,  158.,  414.,  177.,  346.,  111.,
        573.,  277.,  191.,  318.,  411.,  244.,  605.,  192.,  207.,
        155.,  189.,  185.,  162.,  187.,  313.,  557.,  281.,  463.,
        186.,  797.,  214.,  449.,  153.,  296.,  650.,  759.,  286.,
        525.,  246.,  526.,  397.,  645.,  575.,  401.,  348.,  510.,
        122.,  179.,  167.,  691.,  202.,  136.,  151.,  617.,  146.,
        294.,  317.,  175.,  717.,  435.,  405.,  616.,  137.,  152.,
        206.,  415.,  460.,  707.,  319.,  426.,  555.,  480.,  121.,
        430.,  159.,  378.,  321.,  344.,  133.,  232.,  142.,  278.,
         78.,  258.,  264.,  118.,   76.,  788.,  131.,  148.,  203.,
        253.,  312.,  467.,  168.,  156.,  353.,  545.,  422.,  451.,
        197.,  386.,  778.,  521.,  495.,  621.,  456.,  279.,  540.,
        104.,  372.,  366.,  284.,  556.,  193.,  393.,  198.,  298.,
        145.,  242.,  243.,   70.,  610.,  141.,  217.,  533.,  262.,
        342.,  483.,  109.,  231.,  473.,  324.,  443.,  101.,  322.,
        126.,  638.,  710.,  154.,  808.,  143.,  602.,  363.,  178.,
        580.,  624.,  379.,  502.,  470., 1020.,  572.,  702.,  660.,
        341.,  222.,  729.,  417.,  482.,  224.,  176.])